Update initial patch to support TLS 1.3
golang-fips/go pull request #43
Opened 2022-09-13 05:08 UTC by ueno

This patch enables TLS 1.3 even in FIPS mode.  To make the implementation FIPS compliant, it also delegates ECDH and HKDF operations to the FIPS certified library (openssl) through the openssl-fips package.

Signed-off-by: Daiki Ueno <dueno@redhat.com>

2022-09-19 02:10 UTC, ueno commented
Rebased against the latest main branch and tested with `release-branch.go1.19`.

2022-09-20 17:52 UTC, simo5 approved these changes
LGTM,

(a bit hard to read a diff of a patch, it may be nice to provide a link to a git tree where the patches are directly applied to the code in the future, just for better navigability and reference.)

2022-09-20 20:05 UTC, derekparker commented
Getting a few failures when running `./all.bash` after applying patches:

```
--- FAIL: TestBoringServerProtocolVersion (0.00s)
    --- FAIL: TestBoringServerProtocolVersion/VersionTLS13#01 (0.00s)
        handshake_server_test.go:63: Got error: <nil>; expected to match substring 'client offered only unsupported versions'
--- FAIL: TestBoringClientHello (0.00s)
    boring_test.go:285: client offered disallowed version 0x304
    boring_test.go:290: client offered disallowed suite 0x1303
    boring_test.go:290: client offered disallowed suite 0x1301
    boring_test.go:290: client offered disallowed suite 0x1302
FAIL
```

2022-09-20 20:05 UTC, derekparker requested changes
Test failures.

2022-09-26 16:41 UTC, derekparker approved these changes
Tested on RHEL8 in FIPS and non-FIPS modes, everything seems good.

LGTM

2022-09-27 00:53 UTC, merged

2022-09-27 00:54 UTC, ueno commented
Thank you for the review!