Draft: Add Crypto TestConfig
golang-fips/go pull request #75
Opened 2023-01-19 21:54 UTC by dbenoit17

Variations in behavior between OpenSSL versions and distributions often causes the crypto test suite to be incompatible when porting between linux distros. This PR introduces a TestConfig backend for more easily configuring the crypto test suite in FIPS mode.

To configure which algorithms and key types are supported by OpenSSL, adjustments can now be made to the paramaters in

crypto/internal/backend/boringtest/config.go

2023-01-19 21:57 UTC, dbenoit17 commented
I'm making this a draft because this PR depends on:
https://github.com/golang-fips/openssl-fips/pull/37
https://github.com/golang-fips/openssl-fips/pull/46

Once those are updated, we should also update the openssl-fips ref as part-of this pull request.

2023-01-19 22:54 UTC, derekparker requested changes

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	} else if boringtest.Supports(t, "CurveP224") {
Should this be predicated by `boring.Enabled`?

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++				if boringtest.Supports(t, "CurveP224") {
Should this be predicated by `boring.Enabled`?

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	if boringtest.Supports(t, "CurveP224") {
Should this be predicated by `boring.Enabled`?

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++var TestConfig map[string]bool
I don't think we need to export this, all callers seem to use the already exported `Supports()` function.

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	if boring.Enabled && ! boringtest.Supports(t, "PKCSv1.5") {
nit: Do you mind cleaning up the space in the negation operator? E.g. `!assertion()` as opposed to `! assertion()`.

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	if boring.Enabled && ! boringtest.Supports(t, "PKCSv1.5") {
nit: Do you mind cleaning up the space in the negation operator? E.g. `!assertion()` as opposed to `! assertion()`.

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	if boring.Enabled && ! boringtest.Supports(t, "PKCSv1.5") {
nit: Do you mind cleaning up the space in the negation operator? E.g. `!assertion()` as opposed to `! assertion()`.

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	if boring.Enabled && ! boringtest.Supports(t, "PKCSv1.5") {
nit: Do you mind cleaning up the space in the negation operator? E.g. `!assertion()` as opposed to `! assertion()`.

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	if boring.Enabled && ! boringtest.Supports(t, "PKCSv1.5") {
nit: Do you mind cleaning up the space in the negation operator? E.g. `!assertion()` as opposed to `! assertion()`.

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	if boring.Enabled && ! boringtest.Supports(t, "SHA1") {
nit: Do you mind cleaning up the space in the negation operator? E.g. `!assertion()` as opposed to `! assertion()`.

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	if boring.Enabled && ! boringtest.Supports(t, "SHA1") {
nit: Do you mind cleaning up the space in the negation operator? E.g. `!assertion()` as opposed to `! assertion()`.

2023-01-19 22:54 UTC, derekparker commented on patches/000-initial-setup.patch
> ++	if boringtest.Supports(t, "CurveP224") {
Should this be predicated by `boring.Enabled`?

2023-01-20 01:39 UTC, dbenoit17 commented
Current test run:
https://github.com/golang-fips/release/actions/runs/3963814879/jobs/6792076390

2023-01-20 19:00 UTC, derekparker approved these changes
LGTM

2023-01-20 19:02 UTC, merged